
name: CI and Image Build

on:
  pull_request:
  push:
    branches:
      - release
      - master
  workflow_dispatch:

jobs:
  docker:
    name: Docker Build
    runs-on: ubuntu-latest
    steps:
      - name: "Check out repository"
        uses: actions/checkout@v3

      - name: "Build Docker image"
        run: docker build -t mc-server:latest  .

  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    needs: docker
    if: github.event_name == 'push' && github.ref == 'refs/heads/release'

    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: Set image name
        id: image
        shell: bash
        run: echo "name=ghcr.io/${GITHUB_REPOSITORY,,}" >> $GITHUB_OUTPUT

      - name: Set image tag
        id: tag
        shell: bash
        run: echo "tag=${GITHUB_REF#refs/heads/}" >> $GITHUB_OUTPUT

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Sign in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          target: runtime
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.image.outputs.name }}:${{ steps.tag.outputs.tag }}
          labels: org.opencontainers.image.source=${{ github.repository }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
